
import "./globals.css";
import ClientProviders from "./ClientProviders";

export const metadata = {
  title: "Clickei Bazer",
  description: "Generated by Clickei Bazer",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`  antialiased`}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
